### ISSUE TITLE
standardisation functions won't work

### ISSUE THREAD

**Issue by eloyfelix** [eloyfelix/RDKitMinimalLib.jl#2]
Julia can't find the files needed for the standardisation functions

```julia
julia> using RDKitMinimalLib

julia> mol = get_mol("CC(=O)Oc1ccccc1C(=O)O")
RDKitMinimalLib.Mol(Base.RefValue{Cstring}(Cstring(0x00007f98fae74520)), Base.RefValue{UInt64}(0x0000000000000151))

julia> cleanup(mol)
libc++abi.dylib: terminating with uncaught exception of type RDKit::BadFileException: Bad input file /Data/MolStandardize/normalizations.txt

signal (6): Abort trap: 6
in expression starting at REPL[5]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 2650 (Pool: 2640; Big: 10); GC: 0
zsh: abort      julia
```

Files exist and can be found

```julia
julia> using RDKit_jll

julia> joinpath(RDKit_jll.artifact_dir, "share/RDKit/Data/MolStandardize/normalizations.txt")
"/Users/efelix/.julia/artifacts/5f74e2a01383410ce3bf5039e69a8d8778c048f5/share/RDKit/Data/MolStandardize/normalizations.txt"
```

I need to check how this could work in Julia but it seems it may need changes in RDKit in order to make it work

**Comment by greglandrum** [comment]
yeah, I have a todo (hopefully to be done relatively soon) to "build in" the default values of the parameter files for those functions.
In the meantime, if you set $RDBASE and have a `Data/MolStandardize` directory with the required files in there things should work.

**Comment by eloyfelix** [comment]
thanks, if you plan to do that bit I'll give it low priority unless there is someone desperately needing to use that functionality from Julia

**Comment by eloyfelix** [comment]
fixed in https://github.com/rdkit/rdkit/pull/4118

PR to Yggdrasil sent: https://github.com/JuliaPackaging/Yggdrasil/pull/3031
