### ISSUE TITLE
substructure search with SMARTS patterns

### ISSUE THREAD

**Issue by SimonEnsemble** [eloyfelix/RDKitMinimalLib.jl#22]
how can I do substructure searches with SMARTS patterns?

e.g. to mimic [this RDKit example](https://www.rdkit.org/docs/GettingStartedInPython.html#substructure-searching), how can I get a mol from a SMARTS pattern, then do substructure search?

```julia
search_pattern = get_mol("ccO") # I think I need the get mol from smarts function? this returns nothing...
molecule = get_mol("c1ccccc1O") # works great
get_substruct_match(molecule, search_pattern) # error b/c search_pattern is nothing.
```

I can make a PR with some examples in the doc strings. e.g. `get_substruct_match` doc string is incorrect/not clear how it works.

**Comment by eloyfelix** [comment]
thank you for reporting. I just fixed the docstrings with the following example. get_qmol (q for query) needs to be used to get the pattern.

```julia
pattern = get_qmol("ccO")
mol = get_mol("c1ccccc1O")
smatch = get_substruct_match(mol, pattern)

```
