### ISSUE TITLE
`get_svg` for multiple matches

### ISSUE THREAD

**Issue by SimonEnsemble** [eloyfelix/RDKitMinimalLib.jl#25]
first, the `get_svg` doc string doesn't tell us we can view substructure matches by passing in a substructure match as a second argument. had to look at the notebook to discover this works.

second, might be neat to show how to modify e.g. the color by passing in a dictionary somehow?

third, can this work when we have multiple substructures?

```julia
using RDKitMinimalLib
smiles = "COc1cc(C=O)ccc1O" # Vanillin = 4-Hydroxy-3-methoxybenzaldehyde
molecule = get_mol(smiles)
pattern4 = get_qmol("a")
smatch4 = get_substruct_matches(molecule, pattern4)
HTML(get_svg(molecule, smatch4[1])) # works
HTML(get_svg(molecule, smatch4)) # error
```
gives

```julia
MethodError: no method matching get_svg(::RDKitMinimalLib.Mol, ::Vector{Any})
```

**Comment by eloyfelix** [comment]
1 - I'll try to improve the documentation but I'm unfortunatelly not coding much in Julia lately. PRs accepted! 
2 - It is possible but I needed to dig into RDKit code to find how to do it:

to highlight in green

```julia
svg = get_svg(mol, merge(smatch, Dict{String, Any}("height" => 350, "width" => 350, "highlightColour" => [0, 1, 0])))
```


3 - I'd need to check the underlying C library but I think it didn't work like this

**Comment by eahenle** [comment]
Getting an SVG with highlighting for multiple matches just requires concatenating the results like so:
![image](https://user-images.githubusercontent.com/16201240/196051320-c3154f80-e17b-49e1-8a25-2e373e41092c.png)

I'll make a PR
