### ISSUE TITLE
Reaction SMARTS

### ISSUE THREAD

**Issue by jmyounk** [eloyfelix/RDKitMinimalLib.jl#28]
I have a need to perform chemical reactions on rdkit molecule objects with SMARTS patterns.  Would it be possible to have that capability added?

https://www.rdkit.org/docs/source/rdkit.Chem.rdChemReactions.html

**Comment by eloyfelix** [comment]
I spotted some new functionality related to reactions in the MinimalLib but I'm not sure if it will be enough. It might be worth for you to open a discussion in the rdkit github repo telling what you want to achieve and asking if the required functionality could be added to the lib.

Happy to wrap it if it gets included. On the meanwhile I'll wrap the new functionality in the latest build for Julia: https://github.com/JuliaPackaging/Yggdrasil/commit/50255359bbbba66168d04b2ef5b9470c4a4b545a

**Comment by eloyfelix** [comment]
I just wrapped the available functionality and it seems it is only for drawing

<img width="674" alt="Screenshot 2022-10-31 at 09 57 19" src="https://user-images.githubusercontent.com/1122541/198981741-f50f8beb-6fad-46bf-af72-555410a21ecc.png">
