### ISSUE TITLE
GetNumAtoms and RenumberAtoms

### ISSUE THREAD

**Issue by Nick-Mul** [eloyfelix/RDKitMinimalLib.jl#31]
Thanks for putting this package together, looks really useful. 

I was wondering how I might do this this in julia, I couldn't obviously find a way of doing this in RDKitMinimal or MolecularGraphs? 

```
def randomize_smiles_atom_order(self, smiles):
        mol = Chem.MolFromSmiles(smiles)
        atom_idxs = list(range(mol.GetNumAtoms()))
        np.random.shuffle(atom_idxs)
        mol = Chem.RenumberAtoms(mol,atom_idxs)
        return Chem.MolToSmiles(mol, canonical=False)
```

*python code from Esben Bjerrum

**Comment by eloyfelix** [comment]
Hi, random SMILES can be generated like this in RDKitMinimalLib:

```julia
mol = get_mol("CC(=O)Oc1ccccc1C(=O)O")
for i in 1:10
    println(get_smiles(mol, Dict{String,Any}("doRandom" => true)))
end
```

I'll try to document a bit better!
